export const clientStateScript = String.raw`
const state = {
  side: 'BUY',
  keystoreUnlocked: false,
  activeVenue: 'predict',
  latestRecommendations: [],
  balances: null,
  startupFacts: null,
  lastPayload: null,
  localEvents: [],
  settingsDirty: { predict: false, polymarket: false },
  refreshInFlight: false,
  refreshTimer: null,
  refreshIntervalMs: 7000,
  refreshFailures: 0,
  lastFullRefreshAt: 0,
  lastStatusLatencyMs: 0,
  marketsLoaded: false,
  routeAuditRunning: false,
  lastConfigSignature: '',
  lastOrdersSignature: '',
  lastEventsSignature: '',
  lastBotActivitySignature: '',
  lastRouteSignature: ''
};

const $ = (id) => document.getElementById(id);

const venueLabel = { predict: 'Predict.fun', polymarket: 'Polymarket' };
const liveStatusLabel = { idle: '未启动', running: '运行中', stopping: '停止中', error: '错误' };
const orderStatusLabel = { OPEN: '已挂单', PENDING_OPEN: '等待确认', PLANNED: '准备提交', FILLED: '已成交', CANCELED: '已撤销', REJECTED: '已拒绝', UNKNOWN: '提交失败' };
const sideLabel = { BUY: '买入', SELL: '卖出' };
const eventLabel = {
  'ui.balance.refresh.requested': '刷新余额',
  'ui.balance.refresh.completed': '余额完成',
  'ui.balance.refresh.failed': '余额失败',
  'ui.startup-facts.requested': '启动检查',
  'ui.startup-facts.completed': '检查完成',
  'ui.startup-facts.failed': '检查失败',
  'ui.route-audit.requested': '全站审计',
  'ui.route-audit.progress': '审计进度',
  'ui.route-audit.completed': '审计完成',
  'ui.route-audit.failed': '审计失败',
  'ui.live.start.requested': '开启实盘',
  'ui.live.start.warning': '启动提示',
  'ui.live.preflight.started': '实盘预检',
  'ui.live.preflight.passed': '预检通过',
  'ui.live.preflight.failed': '预检失败',
  'ui.live.start.failed': '启动失败',
  'ui.live.start.noop': '已经运行',
  'ui.live.loop.started': '循环启动',
  'ui.live.auto-resumed': '自动恢复',
  'ui.live.resume.skipped': '恢复跳过',
  'ui.live.resume.failed': '恢复失败',
  'ui.live.retrying': '断线重试',
  'ui.live.cycle.started': '循环开始',
  'ui.live.cycle.completed': '循环完成',
  'ui.live.risk-stop': '总止损停机',
  'ui.live.stop.requested': '停止请求',
  'ui.live.stop.noop': '无需停止',
  'ui.live.stop.waiting': '等待停止',
  'ui.live.loop.stopped': '真正停止',
  'ui.live.stop-and-cancel.requested': '停止撤单',
  'ui.live.stop-and-cancel.completed': '撤单完成',
  'ui.live.stop-and-cancel.failed': '撤单失败',
  'route.selection': '市场选择',
  'risk.account-snapshot.unavailable': '账户数据不可用',
  'risk.account-gate.blocked': '账户风控阻断',
  'risk.daily-loss-limit': '总止损阻断',
  'risk.balance-skip': '资金跳过',
  'risk.inventory-skip': '库存跳过',
  'open-orders.unavailable': '开放订单同步失败',
  'positions.unavailable': '持仓同步失败',
  'balance.empty': '余额为空',
  'balance.unavailable': '余额不可用',
  'orderbook.unavailable': '盘口不可用',
  'risk.market-guard.route-reject': '市场未通过',
  'risk.market-guard.reject': '订单风控拒绝',
  'risk.market-guard.final-reject': '最终盘口拒绝',
  'risk.reject': '订单风控拒绝',
  'risk.final-reject': '最终风控拒绝',
  'risk.submit-blocked': '提交前阻断',
  'quote.skip-existing': '已有挂单',
  'quote.adopt-existing': '接管已有挂单',
  'quote.replace-cancel': '撤换旧单',
  'quote.replace-deferred': '撤换延后',
  'order.submitted': '订单已提交',
  'order.submit-pending-verification': '订单待确认',
  'order.submit-error': '提交失败',
  'split.pair-submit-pending-confirmation': '双边待确认',
  'split.pair-submit-verified': '双边已确认',
  'split.pair-submit-unverified': '双边未确认',
  'split.pair-incomplete-cancel': '双边撤回',
  'split.pair-submit-rollback': '提交回滚',
  'split.entry.blocked': '拆分被阻断',
  'split.entry.started': '开始拆分',
  'split.entry.submitted': '拆分已提交',
  'split.entry.verified': '套仓已确认',
  'fill.merge-submitted': '套仓合并',
  'fill.merge-not-ready': '无法合并',
  'fill.merge-unsupported': '合并不可用',
  'fill.cancel-before-merge': '合并前撤单',
  'fill-circuit-breaker.triggered': '成交保护',
  'fill-circuit-breaker.hold': '保护保持',
  'fill-circuit-breaker.cancel-managed': '保护撤单',
  'cash-fill.exit-submitted': '止损退出',
  'cash-fill.exit-blocked': '退出阻断',
  'cash-fill.exit-failed': '退出失败',
  'cash-fill.exit-unsupported': '退出不支持',
  'ui.stop-and-cancel.started': '撤单开始',
  'ui.stop-and-cancel': '撤单完成',
  'ui.cancel-all.started': '撤单开始',
  'ui.cancel-all': '撤单完成',
  'ui.live-loop.error': '循环错误'
};
const riskReasonLabel = {
  ok: '允许新增挂单',
  'snapshot-unavailable': '数据不可用',
  'snapshot-stale': '数据过期',
  'daily-loss-limit': '总止损触发',
  'equity-drawdown-limit': '权益回撤触发'
};
const riskMeta = {
  orderSizeUsd: ['目标挂单金额', 'USD', 'split 模式下是完整 YES/NO 卖单组总预算；非 split 模式下是单笔目标金额。'],
  maxSingleOrderUsd: ['单笔订单上限', 'USD', '任何单笔订单都不能超过这个金额。'],
  maxPositionUsd: ['最大持仓敞口', 'USD', '单个市场/Token 最多允许暴露的资金规模。'],
  maxDailyLossUsd: ['本轮总止损金额', 'USD', '从点击开始实盘后累计；达到该金额后撤机器人受管挂单并停止实盘，直到手动重新开启。'],
  maxAccountRiskStaleMs: ['账户风控有效期', 'ms', '成交、仓位、余额和权益快照超过该时间就禁止新增挂单。'],
  maxOpenOrderReserveDriftUsd: ['冻结偏差上限', 'USD', '开放订单估算占用和平台真实冻结余额允许的最大美元偏差。'],
  maxOpenOrderReserveDriftPct: ['冻结偏差上限', '%', '开放订单估算占用和平台真实冻结余额允许的最大百分比偏差。'],
  settlementNoNewOrdersMs: ['临近结束停新单', 'ms', '距离市场结束少于该时间时，不再新增挂单。'],
  settlementCancelOpenOrdersMs: ['临近结束撤旧单', 'ms', '距离市场结束少于该时间时，撤掉机器人开放订单。'],
  shortEventMaxDurationMs: ['短时事件识别', 'ms', '开始到结束小于该时长的市场，会额外使用开赛/事件开始保护。'],
  eventStartNoNewOrdersMs: ['临近开始停新单', 'ms', '短时赛事/事件开始前少于该时间时，不再新增挂单。'],
  eventStartCancelOpenOrdersMs: ['临近开始撤旧单', 'ms', '短时赛事/事件开始前少于该时间时，撤掉开放订单。'],
  blockUnknownEndTime: ['未知结束时间阻断', '布尔', '平台没有明确结束/停止下单时间时，按实盘保守规则禁止新增挂单。'],
  maxBboMoveCents: ['BBO 跳动上限', 'cents', '生成报价到提交前复查之间，中位价跳动超过该值就拒绝提交。'],
  maxSpreadMoveBps: ['价差突变上限', 'bps', '两次盘口扫描之间价差突然扩大或收缩超过该值就视为不安全。'],
  maxOpenOrdersPerMarket: ['每市场挂单数', '笔', '同一个市场最多保留的开放订单数量。'],
  maxMarkets: ['同时做市市场数', '个', '自动做市循环最多覆盖的市场数量。'],
  staleBookMs: ['最终盘口有效期', 'ms', '提交前重读盘口超过该时间就视为过期，不再下单。'],
  minDepthUsdPerSide: ['单边最小深度', 'USD', '买卖任一侧深度不足时不参与该市场。'],
  minPrice: ['最低报价', '概率', '低于该价格的报价会被风控挡住。'],
  maxPrice: ['最高报价', '概率', '高于该价格的报价会被风控挡住。'],
  minSpreadBps: ['最小价差', 'bps', '普通订单低于该价差才阻断；PP maker 单不靠窄价差硬拒绝。'],
  maxSpreadBps: ['最大价差', 'bps', '价差过宽通常代表盘口质量差或波动异常。'],
  requirePostOnly: ['只挂单不吃单', '布尔', '要求订单尽量保持 maker 行为，降低主动成交风险。']
};
const strategyMeta = {
  optimizerMode: ['优化目标', '', '当前固定为积分收益优化，自动优先选择符合奖励规则的市场和报价。'],
  tradingMode: ['报价模式', '', '保守模式选择更靠后的盘口层级，降低主动成交概率。'],
  entryMode: ['入场/库存模式', '', 'cash 表示不做 split/merge，按单边低竞争 PP 机会挂 maker；split 表示先拆完整 YES/NO 套仓后双边 SELL。'],
  quoteSide: ['挂单方式', '', 'cash 模式可选单边 BUY、库存 SELL 或 BUY+库存SELL；split 模式会固定为双边 SELL。'],
  pointsOnly: ['只做奖励市场', '布尔', '开启后只挑选带积分或奖励规则的市场。'],
  acceptingOnly: ['只做可交易市场', '布尔', '开启后过滤关闭、已结算或暂停交易的市场。'],
  autoSelectMarkets: ['自动 PP 路由', '布尔', '开启后每轮自动选择全局最优 PP 市场，无需手动 selectedMarkets。'],
  minMarketLiquidityUsd: ['最低市场流动性', 'USD', '市场总流动性/资金池低于该值时不推荐、不应用。'],
  minRewardLevel: ['LP 奖励等级', '级', '只允许达到该 pp 星级的市场进入推荐和自动做市；5 级最严格。'],
  minRewardSizeMultiplier: ['奖励份额倍数', '倍', '路由和严格模式最低份额门槛倍数；倍数越高可选盘口越少。'],
  enforceRewardMinimum: ['严格最低份额', '布尔', '现金积分模式固定按当前单笔金额筛选平台 PP 最低份额加 1 的盘口。'],
  candidateLimit: ['热盘口扫描数量', '个', '每轮会先全量读取市场元数据；已持仓/已挂单市场优先拉 active 盘口，再给高潜力 hot 和少量 explore 候选拉盘口，避免撞限速。'],
  switchThresholdPct: ['切换优势', '%', '新市场分数超过当前市场多少才自动切换；cash 模式不需要 split/merge gas，split 跨完整套仓市场会额外检查 gas 成本。'],
  gasBufferMultiplier: ['Gas 安全倍数', '倍', '自动 split/merge 前按 RPC 动态估算手续费，再乘以这个倍数留余量。'],
  fallbackSplitMergeGasUnits: ['兜底 Gas', 'gas', '无法精确估算 split/merge 时使用的保守 gas 上限。'],
  minSwitchBenefitMultiplier: ['换池收益倍数', '倍', '跨市场需要重新拆分时，新市场预期额外 PP 价值至少要覆盖 gas 成本的倍数。'],
  minSwitchEdgeAfterGasUsd: ['换池净优势', 'USD', '跨市场切换扣除估算 gas 后至少要留下的最小净优势。'],
  minSafeHoursForSwitch: ['换池安全时长', '小时', '新市场剩余安全做市时间低于该值时，不为了 PP 切换过去。'],
  bnbUsdForGasEstimate: ['BNB估算价', 'USD', '把链上 gas 成本折算成美元做换池门槛；用于策略估算，不是交易价格。'],
  dualSide: ['双边报价', '布尔', 'cash 模式表示允许 BUY+库存SELL；split 模式表示 YES/NO 两边完整套仓 SELL。'],
  quoteRefreshMs: ['扫描间隔', 'ms', '盘口扫描、撤换单和成交检查之间等待的时间。'],
  marketRefreshMs: ['市场刷新间隔', 'ms', '市场列表和推荐缓存时间，避免每轮都全量扫市场。'],
  conservativeDepthLevel: ['保守盘口层级', '层', '保守模式参考的盘口深度层级。'],
  aggressiveDepthLevel: ['激进盘口层级', '层', '激进模式参考的盘口深度层级。'],
  retreatTicks: ['后退 tick', 'tick', '报价从目标价向后退让的最小价格步数。'],
  replaceThresholdTicks: ['撤换阈值', 'tick', '目标报价移动超过这个 tick 数时，自动撤旧单并换到新奖励位置。'],
  cancelOutsideReward: ['奖励外撤单', '布尔', '市场或订单不再符合积分筛选时，自动撤掉该机器人管理的旧单。'],
  onFillAction: ['split 退出动作', '', 'split 完整 YES/NO 套仓可合并退出；cash 单边被吃后的退出由 cashOnFillAction 控制。'],
  cashOnFillAction: ['cash 被吃后动作', '', 'hold 表示撤单后暂停；sellWithinLossCap 表示在亏损上限内发 SELL taker 限价退出。'],
  cashMaxExitLossPct: ['退出亏损上限', '%', '被吃出持仓后，只有当前 SELL 退出价格仍在这个亏损上限内才会提交卖单；超过上限不扫穿。'],
  liquidationSlippageTicks: ['旧卖出参数', 'tick', '保留旧配置兼容；当前 split 实盘退出不使用市价卖出。'],
  liquidationMaxSlippageCents: ['旧滑点参数', 'cents', '保留旧配置兼容；cash 退出使用 cashMaxExitLossPct。'],
  minPositionSizeToLiquidate: ['最小合并份额', '份', '完整 YES/NO 套仓低于该份额时不触发合并退出。'],
  balanceReserveUsd: ['余额保留', 'USD', '自动挂单前预留这部分余额，不用于下单。'],
  inventorySkewEnabled: ['偏仓保护', '布尔', '已有持仓过高时不继续加同方向买单，降低单边暴露。'],
  maxInventorySkewUsd: ['最大偏仓', 'USD', '达到该 token 偏仓规模后停止继续买入。'],
  dedupeMarketGroups: ['市场分组去重', '布尔', '同一赛事/问题下限制 token 数，避免资金集中在一个市场。'],
  maxTokensPerMarket: ['单市场 Token 上限', '个', '同一个市场分组最多允许几个 outcome token 进入推荐和做市。']
};
`;
